# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ggen < Formula
  desc "ggen is a simple CLI tool via Golang."
  homepage "https://github.com/Nabby12/ggen"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nabby12/ggen/releases/download/v0.0.1/ggen_Darwin_x86_64.tar.gz"
      sha256 "9be4f07699608afbeae0d4950ad5b89149502282815ba27982ec0ada78af0b1a"

      def install
        bin.install "ggen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nabby12/ggen/releases/download/v0.0.1/ggen_Darwin_arm64.tar.gz"
      sha256 "e7c325d1e3237c4580dcb50df96f9f7bdb8d951fb1b16ef9ec253c8405382bd9"

      def install
        bin.install "ggen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Nabby12/ggen/releases/download/v0.0.1/ggen_Linux_x86_64.tar.gz"
      sha256 "738939f3e54d531b142c5cae002d140f49bbfc437491f7866efa590aff096a24"

      def install
        bin.install "ggen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nabby12/ggen/releases/download/v0.0.1/ggen_Linux_arm64.tar.gz"
      sha256 "caa505fadf877b366bc731914c1657d38a3cf8ad65704f0d549ddedc10d11f5d"

      def install
        bin.install "ggen"
      end
    end
  end
end
