# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ggen < Formula
  desc "ggen is a simple CLI tool via Golang."
  homepage "https://github.com/Nabby12/ggen"
  version "0.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nabby12/ggen/releases/download/v0.0.0/ggen_Darwin_x86_64.tar.gz"
      sha256 "307177543c5442329b8ed478f658c74b860b968596ea404855fe5c828e0ea1a4"

      def install
        bin.install "ggen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nabby12/ggen/releases/download/v0.0.0/ggen_Darwin_arm64.tar.gz"
      sha256 "86041099c56dbdd120b6d60b2cd6b18072467be41aefa4ca51850782ca1262b0"

      def install
        bin.install "ggen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nabby12/ggen/releases/download/v0.0.0/ggen_Linux_arm64.tar.gz"
      sha256 "d046aeb7624ee61d0ea4cc146d27001ba2819e0de1544dbdaae2f0e7c4d0d0cd"

      def install
        bin.install "ggen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Nabby12/ggen/releases/download/v0.0.0/ggen_Linux_x86_64.tar.gz"
      sha256 "997a169364e962f9d99310214bba57403e877d7b78e7db1058c01a22be76df17"

      def install
        bin.install "ggen"
      end
    end
  end
end
